management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: 'Homework-Spring Application'
    descrption: "Application for homework"
    version: 1.0.0

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/springHW?createDatabaseIfNotExist=true'
    username: 'root'
    password: 'root'
  jpa:
    database-platform: 'org.hibernate.dialect.MySQL5InnoDBDialect'
    hibernate:
      ddl-auto: create
    show-sql: true

app:
  user:
    password: password
    email: email@email.com
